pyblish/pyblish-qml

- pyblish_qml/models.py
- pyblish_qml/qml/Overview.qml
Labels now use verbs as opposed to nouns.
"Validators" -> "Validate"
"Extractors" -> "Extract"
Such that you can use names of your plug-ins to match.
"Validate bind pose"
"Extract Maya ASCII"
Etc.
> Minor cosmetics

- pyblish_qml/compat.py
- pyblish_qml/qml/Overview.qml
- pyblish_qml/qml/Pyblish/ListItems/SectionItem.qml
- pyblish_qml/qml/Pyblish/ListItems/qmldir
Updated compatibility test.
```bash
python -m pyblish_qml.compat
```
And refactored the QML SectionItem.
@tokejepsen There are two changes to the code you committed yesterday.
1. SectionItem became it's own file, next to other list items, just to make `Overview.qml` smaller and more readable.
2. The "imperative" code where things happen at an event are now "declarative" instead; this is the QML way and works due to the so called "bindings". Every attribute will automatically update itself once the expression changes, in this case, then the item is hovered or pressed. It's one of the differences between Python and QML and takes some getting used to, but it's really cool I think!
I've attempted to bring some of the binding-functionality into Python via the model; as you may have noticed, …
> Cosmetics and stability

- pyblish_qml/control.py
https://github.com/pyblish/pyblish/pull/238
> Data Handlers

- pyblish_qml/control.py
- tests/test_control.py
Removed some references to deprecated `set_data()` members and improved coverage of tests.
Also discovered that the `item_model` in the controller keeps two independent collections of its items. This was done early to simplify retrieving an instance, but never accounted for the fact that items may change after they had been added.
- [self.instances = ItemList()](https://github.com/pyblish/pyblish-qml/blob/87cf2c8dfe500e5dd41d9d6c8e0005a45f3445ff/pyblish_qml/models.py#L283)
I've patched it up now, but not very nicely. A better alternative would be to lose the additional caches and include methods on the model for retrieving them dynamically based on just one list; the `items` list. I've added a TODO to the section in the controller where this improvement would make a difference.
> Modified tests

- pyblish_qml/qml/List.qml
Quite a huge mistake which meant Action icons weren't showing at all.
Clearly my test was not good at all :disappointed:
> - fixing qml typo

- .travis.yml
- .travis/install.sh
- .travis/install_linux.sh
- pyblish_qml/control.py
- pyblish_qml/models.py
- pyblish_qml/qml/Pyblish/ScrollHint.qml
- pyblish_qml/qml/Pyblish/qmldir
- pyblish_qml/qml/app.qml
- pyblish_qml/qml/tests/tst_NewModel.py
- pyblish_qml/qml/tests/tst_NewModel.qml
- tests/test_control.py
GUI works, but some tests fail!
> Work in progress of new ID-based items

- pyblish_qml/qml/Pyblish/Theme.qml
was giving the following error on linux
``` bash
pyblish_qml/qml/Pyblish/Theme.qml:98:5: QML FontLoader: Cannot load font: "file:///software/rez/user_packages/lars/pyblish_qml/0.6.0/python/pyblish_qml/qml/Pyblish/fonts/opensans/OpenSans-SemiBoldItalic.ttf"
pyblish_qml/qml/Pyblish/Theme.qml:97:5: QML FontLoader: Cannot load font: "file:///software/rez/user_packages/lars/pyblish_qml/0.6.0/python/pyblish_qml/qml/Pyblish/fonts/opensans/OpenSans-SemiBold.ttf"
```
> fixed typo

- pyblish_qml/control.py
- tests/test_control.py
Fixes Bug, if a plugin is set active=False and you manually activate it again, it won't get executed
> removed if not plug.active

- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
Not setting `PYBLISH_QML_PYQT5` implies an automatic search for PyQt5 on the provided Python's PYTHONPATH. But, the search is moot considering Python would already be searching for it when attempting to run the app. This meant that during startup, Python was instantiated twice; once to find PyQt5, and once to actually use it.
Assuming Python implies reading 50 mb off disk, this reduces the amount read from 100 mb to 50 mb, which in addition to PyQt5 libraries at another 50 mb means a (max) 33% reduction in startup time. In reality it will be less due to filesystem caching.
> Improve startup performance

- .gitignore
- pyblish_qml/app.py
- pyblish_qml/version.py
Alert the window on `controller.finished signal`
> Implement #227 

- README.md
- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/host.py
- pyblish_qml/ipc/client.py
- pyblish_qml/ipc/formatting.py
- pyblish_qml/ipc/server.py
- pyblish_qml/ipc/service.py
- pyblish_qml/qml/CommentBox.qml
- pyblish_qml/qml/Footer.qml
- pyblish_qml/qml/Overview.qml
- pyblish_qml/qml/delegates/DocumentationDelegate.qml
- pyblish_qml/util.py
- pyblish_qml/version.py
This PR enables the user to include a comment with his publish.
Implements #9.
**Format**
Comments made via the editor is stored in the `comment` data member of the `context`, as a single block of text.
```python
context.data["comment"] = "Summary goes here\nDescription goes here, on a new line"
```
This is similar to comments on Git commits, the first line being dedicated to a short "summary" of your overall commit, with an (optional) longer description.
You can just add a summary, just add a description, or both. The first line always results in the first line of your comment.
**Features**
- Automatically show comment on presence of `context.data["comment"]`
- Remember comment across resets
- Dedicated signal `commented` for optional data persistence
- Maximisable, type out your …
> Implement support for adding a comment

- pyblish_qml/host.py
- pyblish_qml/settings.py
Currently you can't set the context label or window title on startup of the applications.
> Set the context label and window title, if not already set externally.

- pyblish_qml/app.py
- pyblish_qml/ipc/mocking.py
**Motivation**
This is to add the ability to execute code when the pyblish-qml window is closed.
**Implementation**
Maybe we should have a dedicated "pyblishQmlCloseForced" event emitted as well when closing forcibly?
Also I would like to write a test for the signal as well, but I find it hard to write test for pyblish-qml because I don't have access to Docker. Maybe we could have a ```run_tests.py``` for local testing?
> Emit close signal

- pyblish_qml/control.py
- pyblish_qml/ipc/mocking.py
- pyblish_qml/qml/CommentBox.qml
- pyblish_qml/qml/Overview.qml
- pyblish_qml/version.py
Hi Marcus,
This fixes #249 .
https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/control.py#L603-L615
```python
def on_commenting(self, summary, description):
def update():
comment = "\n".join( entry for entry in self.data["comment"] if entry)   # <= This and...
context = self.host.cached_context
context.data["comment"] = comment
self.data.update({"comment": (summary, description)})  # <= This line must before `comment` declaration
```
* There seems mismatch with updating host's context between updating its content of `self.data`.
* Host receive previous state of `self.data["comment"]`
> Fix #249 Mangled comment

- pyblish_qml/__init__.py
- pyblish_qml/__main__.py
- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/host.py
- pyblish_qml/ipc/formatting.py
- pyblish_qml/ipc/mocking.py
- pyblish_qml/ipc/schema/plugin.json
- pyblish_qml/ipc/server.py
- pyblish_qml/qml/delegates/ContextDelegate.qml
- pyblish_qml/version.py
**Motivation**
This PR is to facilitate the targets workflow that was introduced in https://github.com/pyblish/pyblish-base/releases/tag/1.5.0.
**Implementation**
The implementation for pyblish-qml is done so you can exclusively target plugins. For a demonstration you can execute:
```bash
$ python -m pyblish_qml --demo --targets studio
```
This will only load two plugins that are targeted directly for ```studio```.
To get all plugins you can target both ```default``` and ```studio```:
```bash
$ python -m pyblish_qml --demo --targets default studio
```
You can also specify the targets when showing pyblish-qml from a host:
```python
import pyblish_qml
pyblish_qml.show(targets=["studio"])
```
Because the matching is using ```pyblish.api.plugins_by_targets``` its important to get …
> Targets workflow.

- pyblish_qml/app.py
- pyblish_qml/host.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
Looking for the best way to call pyblish_qml's window actions, like publish, validate, etc
In pylish_lite, we can simply do:
```
window = pyblish_maya.show()
window.publish() #after validation...
```
After chatting [here ](http://forums.pyblish.com/t/call-pyblish-qml-actions/388 )with @mottosso, 
Here's what i came up with.
Usage:
```
import pyblish_qml.host
pyblish_qml.host.publish()
pyblish_qml.host.validate()
```
> Added support for publish and validate from within the host app

- pyblish_qml/models.py
- pyblish_qml/qml/List.qml
- pyblish_qml/version.py
Found that instance's warning state only take effect from the last plugin.
* If warning was not emitted by the last plugin, then it will be override by ~~error or *(it should be)*~~ success.
* If warning was emitted by the last plugin, instance's error state will be override.
---
Thought this should not be a normal ~~instance item~~ log level behavior, I added `persistWarning` into item-model to keep the warning state for instance item, and reset warning state if that instance got error.
---
[Simple test case I used](https://gist.github.com/davidlatwe/37766b311e708a2df988c15852c8fe09)
> fix instance Warning state behavior in GUI

- pyblish_qml/__init__.py
- pyblish_qml/host.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
This PR implements a modal mode and a way to switch between modal and non-modal.
The motivation for a modal mode is because of threading issues in Nuke reported in #264.
**Usage**
Non-modal is the default when using ```pyblish_qml.show()```.
To invoke modal mode you can either explicitly call ```pyblish_qml.show(modal=True)``` or set the environment variable ```os.environ["PYBLISH_QML_MODAL"] = "True"```.
> Modal mode

- pyblish_qml/qml/Message.qml
- pyblish_qml/version.py
> Persist status text until next event.

- pyblish_qml/qml/Pyblish/CheckBox.qml
- pyblish_qml/qml/Pyblish/ListItems/SectionItem.qml
- pyblish_qml/qml/Pyblish/ListItems/StandardActions.qml
Along the theme of section colors, I wanted to see what it'd look like to update the checkbox icon with something other than the check, as check normally means "all good", which isn't the case when things error.
Not sure it's an improvement.. Welcome to tinker.
As I was writing this, I discovered a minor bug in the previously merged PR; namely that the section icon went too dark when unexpanded and had no status.
> Check icon

- Dockerfile
- pyblish_qml/vendor/Qt.py
I had an issue where PySide where not being picked up:
```python
import os
os.environ["QT_VERBOSE"] = "True"
pyblish_qml.show()
Preferred bindings: ['_pyside2', '_pyqt5', '_pyside', '_pyqt4']
Trying _pyside2
ImportError: No module named PySide2
Trying _pyqt5
ImportError: No module named PyQt5
Trying _pyside
ImportError: DLL load failed: The specified module could not be found.
Trying _pyqt4
ImportError: No module named sip
Traceback (most recent call last):
File "<string>", line 2, in <module>
File "C:\Users\admin\development\installation\windows\envs\bumpybox-environment\Lib\site-packages\repositories\pyblish-qml\pyblish_qml\__init__.py", line 11, in show
from . import host
File "C:\Users\admin\development\installation\windows\envs\bumpybox-environment\Lib\site-packages\repositories\pybli …
```
> Update Qt.py to 1.1.0.b10.

- pyblish_qml/ipc/formatting.py
- pyblish_qml/version.py
`pyblish-lite` implements this by omitting the checkbox when an Instance has `.data['optional'] = False`, effectively making an instance "mandatory" (in whatever state it was added.)
With this PR, `pyblish-qml` implements mandatory isntances by greying out the checkbox, just like it's already doing for the "Context" entry in the top left. Clicking on them shows a "Cannot toggle." status prompt.
To show what this looks like, here's a dummy Collector I used:
```python
class Collector(pyblish.api.ContextPlugin):
order = pyblish.api.CollectorOrder
def process(self, context):
instance = context.create_instance('farmer', family='human')
instance.data['optional'] = False
instance.data['publish'] = True
for i in range(3):
instance = context.create_instance('potato%s' % i, family='vegetable') …
```
> Add support for mandatory instances

- README.md
- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/host.py
- pyblish_qml/ipc/client.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
In this PR, should have:
* eventFilter auto remove after quitting under any conditions
- No matter `foster` is on or not, usual window close or force quit, should remove evenFilter in the end.
* Foster mode should work under any versions of Maya
- Behavior may differ by the Qt version on host, in my observation, host which running Qt4 could not render QML window properly while window setParent back to subprocess (*window detach-attach*), which meant for avoiding main thread busy. So in this PR, in order to guaranty the visual feedback, those Qt4 host will not be able to avoid main thread busy (lag better then blank).
- For test propose, you can turn *detach-attach* on or off by setting environment variable `PYBLISH_QML_FOSTER_NINJA=True` or `False` (`Yes/No 1/0`)
* In any condition, …
> Implemented eventFilter removal and improved Foster stability

- .travis.yml
- pyblish_qml/version.py
- setup.cfg
`.travis.yml` is already configured to make a wheel file, but not a universal one.
This fixes that.
> Add setup.cfg to tell bdist_wheel that we want a 'universal' wheel.

- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
This PR will provide two fix:
1. eventFilter get removed when main window minimized.
> did not found this bug on previous PR, sorry :(
2. Comment did not restore back to host after rest, here's the scenario:
1. Artists input comments to QML comment box
2. Validation failed or some other cases that make artist to **press `reset` botton**
3. Comments remain in QML comment box and **did not make any new input**
4. Published, but the comment did not collect to database
> Minor fix: eventFilter drop on minimized; comments lost sync after GUI rest

- pyblish_qml/control.py
- pyblish_qml/version.py
Plugins which using multiple `Category` or `Separator` to organize `Action` may produce an action menu that left some `Category` or `Separator` uncleaned in GUI.
As you can see, in those two action menus, there are an empty `Category` *C* and a `Separator` with no actions to separate.
I like to use `Category`, and with this PR, redundant `Category` and `Separator` would be taken care of.
🍺 🍺 
<details>
<summary>Reproducible Code</summary>
```python
import pyblish.api
class CollectInstances(pyblish.api.ContextPlugin):
order = pyblish.api.CollectorOrder
def process(self, context):
context.create_instance(name="Dummy")
class ActionToAll(pyblish.api.Action):
on = "all"
label = "Action to All"
class ActionOnFailed(pyblish.api.Action):
on = "failed"
label = "Action On Failed"
class …
```
> Fix to remove all empty categories in action menu

- pyblish_qml/control.py
- pyblish_qml/ipc/client.py
- pyblish_qml/qml/Footer.qml
- pyblish_qml/qml/Overview.qml
This PR provide 2 fix and 1 extra feature:
* Fix #281: No need to press twice when section items were all manually toggled on/off.
* Fix #274 and #119: Status message are now more specific.
* Able to press stop on collecting, which I think would be a bit improve on UX.
> Enhancement, fix #281, #274 and #119

- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/qml/Footer.qml
- pyblish_qml/qml/Overview.qml
In previous PR #304, the new feature that allow user to stop collecting process at startup, will make GUI stuck at "Collecting.." phase if the collecting process ended in *short time* (before QML get initialized).
That feature rely on QML to receive the signal `firstRun` to reset those button, so if the signal `firstRun` emitted before QML complete initialization, GUI stocked.
Increase QML initialization waiting time from `500` to `1500`, give it enough time to be ready to receive signal `firstRun`
> Fix #304, increase QML initialization waiting time

- pyblish_qml/control.py
- pyblish_qml/version.py
In the state machine, `extracting` state needs to transition to `finished` if the validation failed during the publish, or the stop button won't change to reset button, and cause user operation not able to continue.
This commit fixed that.
---
Somehow I missed this one in the previous tests, after founding this bug in my work, right after the release of `1.8.6`, I spend a day did a series of user operation flow inspection, including each kind of `Action`, and compared the outcome with previous releases, so far this is the only one that I have missed based on previous PRs.
> Fix state machine transision bug from PR #304

- README.md
- pyblish_qml/__init__.py
- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/host.py
- pyblish_qml/ipc/client.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
After introduced experimental feature *Foster Mode* since [`v1.8.0`](https://github.com/pyblish/pyblish-qml/releases/tag/1.8.0), it also spawned a few bugs which related to DCC app's threading, although those bugs seems to be fixed, but the confidence on this feature did not bounce back.
Remove experimental window *fostering* feature from master branch for not being a potential obstacle on further development. The version will bump to `1.9.0`
[Comparing against v1.7.4](https://github.com/pyblish/pyblish-qml/compare/1.7.4...b48efeb)
The feature `Foster Mode` will remain available on my forked branch [`dev-foster`](https://github.com/davidlatwe/pyblish-qml/tree/dev-foster), and will try to update along with the latest master.
Please let me know what you think on this.
> Foster Mode Deprecated

- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
While working on a modal pyblisher, I encountered an issue where the QML client closed itself with no return code after 15 seconds.
After investigation, it seem the cause of the issue is that the pulse thread (which notify the client that the server is still alive) is created after the main logic thread. If the pyblisher is modal, the main logic is not a thread and hence will prevent the pulse thread from being created in time. 
This issue can be easily reproduced by opening a modal pyblisher in any host with pyblish_qml-1.9.0+.
This PR move the creation of the pulse thread before the main logic.
> Ensure pulse thread is created before we start listening

- pyblish_qml/host.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
Building upon #320, this PR adds support for Blender.
The trick here is passing data between threads using a native Queue. A polling operator is added to Blender, which continuously polls a queue for things to do. When QML has a task for Blender, it's added to this queue, Blender runs it, and adds to another queue for QML to pick up the result.
It's currently running at 10 ms intervals, including when the GUI isn't visible, which isn't ideal and could be optimised away. E.g. stop polling when GUI is closed.
> Blender Support

- pyblish_qml/host.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
Without `PYBLISH_QML_PYQT5`, the wrong path got automatically registered causing Qt binaries to be exposed to the Pyblish QML process (e.g. PySide2 binaries for a PyQt5 application).
Also when the above error occurred, the event filter was supposed to get uninstalled, but was not. That's fixed here too.
> Windows Bug Fixes

- pyblish_qml/host.py
This fixes the bug that QML only install eventFilter once on first run :)
(Missed this one because I only tried running it once in Maya while testing previous PR)
> Always try to install on show

- pyblish_qml/ipc/client.py
- pyblish_qml/version.py
Depending on when threads print to stdout, there is a chance that the IPC gets stuck forever. The easiest explanation/demo is the following:
```
import sys
import threading
import time
def ipc_communication_thread():
while True:
msg = '{"json": "yes"}'
sys.stdout.write(msg + "\n")
sys.stdout.flush()
def anything_else():
while True:
print "logging something"
t0 = threading.Thread(target=ipc_communication_thread)
t0.daemon = True
t1 = threading.Thread(target=anything_else)
t1.daemon = True
t0.start()
t1.start()
time.sleep(2)
```
Looking at the output the problem is readily apparent:
> ...
> {"json": "yes"}
> logging something{"json": "yes"}
> 
> logging something{"json": "yes"}
> 
> logging something{"json": "yes"}
> 
> {"json": "yes"}
> logging something
> {"json": "yes"}
> ...
The `print` …
> Fix occasional ipc deadlock

- pyblish_qml/control.py
- pyblish_qml/ipc/server.py
- pyblish_qml/models.py
- pyblish_qml/version.py
The implementation of #315, which aim to keep the GUI to display the latest status data change of instances, like `optional`, `publish`, `families`.
Currently, once the plugin which responsible to create the instance, has been processed, the change of the instance data that made by other plugins will not reflected to GUI. For example, the newly added family will not be shown in Perspective View, and setting `publish` to False will not toggle instance off.
Not good to merge yet.
> Implementing #315

- pyblish_qml/__init__.py
- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/host.py
- pyblish_qml/version.py
These are some features to streamline the usage of pyblish-qml in our pipeline. They are implemented backwards compatible,  no previous usage/behaviour is expected to break.
Basically we have our own UI that deals with all the instance/plugin config. This means when we call the pyblish-qml app, everything is already set up. Our changes are related to automation:
1. One of the added features is a new argument to `show(... , auto_publish_at_first_run=False)`. This saves the user the wait for the reset and the click on the publish button.
1. Another added feature is also a new argument to `show(... , comment=None)`. In our system the user needs to input the comment earlier than the pyblish process can be started, so we wish to be able to pass it along to pyblish-qml.
1. Lastly, two API entry …
> Some QoL features for integration

- pyblish_qml/ipc/client.py
- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
This contains a fix for #327 while re-applying #325 .
The async consumption of a sync queue discovered during the investigation of #327 is a separate problem:
- This fix ensures different threads on the client side that print will not mess up the communication.
- While the async consumption of messages is a design issue where two legitimate communication procedures may encounter a race condition.
I propose that a new issue should be opened for the async problem.
> Re-apply #325 and fix #327

- Dockerfile
The Ubuntu `17.10` docker image seems dead now, so the CI keeps failing.
Bump Ubuntu image version to `18.10` solved this issue
> Bump ubuntu docker image version

- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
After PR #320, `WindowsError: [Error 6]` raised in Houdini while `PyQt5` lookup at this line [here](https://github.com/pyblish/pyblish-qml/blob/e93b144f7c0bf7ea5606e8449399d77ef4943753/pyblish_qml/ipc/server.py#L392).
I changed from using `subprocess.check_output` to `Popen` still getting same error.
It seems something to do with `subprocess.PIPE`.
Not sure if this is the right fix, but for what I can do now is adding `WindowsError` exception.
---
The main issue was we need both `stdin` and `stdout` set to `subprocess.PIPE` in order to work inside Houdini ( without Administrator privilege ).
So here's the main changes for working in Houdini:
* Add `stdin=subprocess.PIPE`
* Run `check_output` with clean environment
> WindowsError raised in Houdini after #320

- pyblish_qml/ipc/server.py
- pyblish_qml/version.py
Still getting redundant newline after #329.
It looks like previous fix missed out to catch *regular message*, and stripping them solved the issue.
So this PR seems to be the last puzzle of #329.
> Fix redundant newline from #329

- pyblish_qml/host.py
- pyblish_qml/version.py
So far this is the only thing I encountered that didn't work in Blender 2.80.
This simple fix should make it work in both Blender 2.79 and Blender 2.80.
> Fix: make `window` a keyword argument for Blender 2.8 compatibility

- pyblish_qml/control.py
This fixes the Instance's label not updating when it's changed by a Collector later in the chain. Now it will correctly update.
See:
Reference:
- [Pyblish Gitter Discussion about instance label not updating in Pyblish QML](https://gitter.im/pyblish/pyblish?at=5d3856a7be916e76e22b264f)
> Update label as it's changed in instance.data["label"]

- pyblish_qml/models.py
This is a fix for #341 where the *"A"* Actions icons was visible on plug-ins when Categories were added to the actions yet there was not action currently available to run.
**What's changed?**
When deciding whether to enable `actionsIconVisible` we ignore any action which his `__type__` is not set to `action`, which is [the the case for Categories](https://github.com/pyblish/pyblish-base/blob/841f40821507964389adac01683ac86f745bb5fe/pyblish/plugin.py#L419). As such, now only whenever an action is available for processing with `__type__ == "action"` the icon will be visible on the plug-ins.
> Fix #341: Ignore Categories when deciding to show Actions icon on plug-ins

- pyblish_qml/control.py
This PR resolves #343, footer will show failed message if any instance got error during extraction or integration.
> Prompt failed message at the end if any error occurred after validation (default test)

- pyblish_qml/control.py
- pyblish_qml/version.py
Also fixes #333, also see https://github.com/pyblish/pyblish-base/pull/355
I'm not using this in production at the moment, so keep an eye out for anything you find missing. I suspect the GUI might have trouble displayin the message previously passed on from StopIteration, such as when validation failed.
> Python37support

- pyblish_qml/control.py
- pyblish_qml/version.py
GUI message prompting like showing "validated", "failed validation", and "published with error" was broken after #349, this PR resolves that side-effect. :relaxed: 
Hooray on Python3.7 supported :tada:
> Fix GUI message prompting after #349

- pyblish_qml/vendor/Qt.py
- pyblish_qml/version.py
When trying to launch Pyblish QML in Maya 2020, the following error raised.
```python
File "C:\Users\david\Dropbox\github\AVALON\pyblish-qml\pyblish_qml\host.py", line 290, in __init__
from .vendor.Qt import QtWidgets, QtCore, QtGui
File "C:\Users\david\Dropbox\github\AVALON\pyblish-qml\pyblish_qml\vendor\Qt.py", line 1557, in <module>
_install()
File "C:\Users\david\Dropbox\github\AVALON\pyblish-qml\pyblish_qml\vendor\Qt.py", line 1509, in _install
available[name]()
File "C:\Users\david\Dropbox\github\AVALON\pyblish-qml\pyblish_qml\vendor\Qt.py", line 1037, in _pyside2
_reassign_misplaced_members("PySide2")
File "C:\Users\david\Dropbox\github\AVALON\pyblish-qml\pyblish_qml\vendor\Qt.py", line 922, in _reassign_misplaced_members
dst_value = getattr(getattr(Qt, "_" + src_module), …
```
> Update vendorized Qt.py

- Dockerfile
- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/models.py
- pyblish_qml/qml/CommentBox.qml
- pyblish_qml/qml/Pyblish/Label.qml
- pyblish_qml/qml/Pyblish/SpinBox.qml
- pyblish_qml/qml/Pyblish/TextField.qml
- pyblish_qml/qml/main.qml
- pyblish_qml/util.py
- pyblish_qml/vendor/Qt5.py
- pyblish_qml/version.py
This will fix #313 and fix #301.
Both #313 and #301 were issues that having `PyQt5` *DLL load failed* error on App startup, and through the tests what @BigRoy has done in #313, looks like it's a problem which possibly came from DCC host about how they load those Qt DLLs, and is hard to solve directly from our end.
So since those DCC were holding DLL which was from `PySide2`, making `PySide2` also usable for `pyblish_qml` could be a good workaround.
* Make QML App able to use `PySide2` as Qt binding with the help from `Qt5.py`.
* Vendorized `Qt5.py`.
May lose font when using `PySide2`.
There's a strange problem after using `PySide2`, is the QML's comment box may display weird characters on first run.
But if we don't assign `font.family` in QML …
> Opt-in PySide2 via Qt5.py

- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/host.py
- pyblish_qml/ipc/server.py
This was reported in Gitter 👉 [February 3, 2020 4:54 PM](https://gitter.im/pyblish/pyblish?at=5e37dfb6fe0e6f74e9fbd502) from @BigRoy .
It was a bug after #347, it was trying to solve #335 which was assigning and changing targets via `pyblish_qml.api.show`. But the solution did not pay attention to the case that is using targets from `pyblish.api.registered_targets`, hence we got the bug.
```python
import pyblish.api
import pyblish_qml.api
pyblish.api.register_target("custom")
pyblish_qml.api.show()
pyblish_qml.api.show()
```
* Only updating targets to current server if `targets` is provided
* Default value of `targets` changes to `None` instead of mutable `list`
> Fix registered targets lost when re-launching on existed server

- pyblish_qml/host.py
This resolves https://github.com/pyblish/pyblish-qml/issues/360
> Fix #360 - quit Pyblish QML when Blender's operator is cancelled

- pyblish_qml/app.py
- pyblish_qml/control.py
- pyblish_qml/ipc/client.py
- pyblish_qml/ipc/server.py
- pyblish_qml/ipc/service.py
- pyblish_qml/util.py
This is a fix for a bug where the registered test function (i.e. the function registered with `pyblish.logic.register_test`) is not passed from the pyblish-qml client to the server, which ends up always using the default test function.
The issue was discussed with more details and a code sample here: https://github.com/pyblish/pyblish-qml/issues/363
> Fix custom registered test not being passed from client to server

- pyblish_qml/version.py
- requirements.txt
- setup.py
Closes #337 
I'm not sure this actually sets the version dependency appropriately, but pyblish-qml almost certainly shouldn't be explicitly depending on such an old version of pyblish-base as it is now.
> Relax pyblish-base version dependency.

- pyblish_qml/qml/List.qml
this PR fixes the following:
when opening QML the console always spams errors 
```
Entering state: "initialising"
Entering state: "collecting"
WARN (bpy.rna): C:\Users\blender\git\blender-v300\blender.git\source\blender\python\intern\bpy_rna.c:1352 pyrna_enum_to_py: current value '0' matches no enum in 'ColorManagedInputColorspaceSettings', '(null)', 'name'
Not ready, hold SHIFT to force an exit
Spent 1286.91 ms resetting
Made 0 requests during publish.
file:///C:/Users/REDACTED/pyblish_qml/qml/List.qml:28: TypeError: Cannot read property 'width' of null
file:///C:/Users/REDACTED/pyblish_qml/qml/List.qml:28: TypeError: Cannot read property 'width' of null
file:///C:/Users/REDACTED/pyblish_qml/qml/List.qml:28: TypeError: Cannot read property 'width' of null …
```
> fix TypeError spam when opening QML
