setup.py

Adding missing package data to PyPI

Fixed issue regarding repairs processing valid instances.

---

pyblish_qml/models.py

https://github.com/pyblish/pyblish-qml/issues/103

Implementing #103

---

pyblish_qml/__init__.py
pyblish_qml/app.py

and changes the default heartbeat rate from 5 seconds to 1…

Fixes #126

---

pyblish_qml/app.py
pyblish_qml/compat.py
pyblish_qml/qml/Pyblish/contextMenu.qml

Now when you close the GUI in debug-mode, the application exits.

More developer friendliness

---

pyblish_qml/qml/Overview.qml

Plugin section toggling

---

CHANGES
pyblish_qml/control.py
pyblish_qml/models.py
pyblish_qml/qml/Footer.qml
pyblish_qml/qml/List.qml
pyblish_qml/qml/Overview.qml
pyblish_qml/qml/Pyblish/CheckBox.qml
pyblish_qml/qml/Pyblish/ListItems/BaseListItem.qml
pyblish_qml/qml/Pyblish/ListItems/StandardActions.qml
pyblish_qml/qml/app.qml
pyblish_qml/qml/main.qml
pyblish_qml/version.py

This implements a number of issues and tweaks!
- Enhancement: Collectors visible during reset (#133)
- Enhancement: Animated feedback on currently running items
- Enhancement: More visible indicator of which is currently running
- Optimisation: Start-up performance; the Window pops up faster thanks for not having to wait for Collectors
- Optimisation: Interactivity performance; pressing buttons doesn't lag anymore (#134)
- Bugfix: Accurate representation of currently running items
- Bugfix: Both family and families are represented in the GUI
- Bugfix: Plug-ins only compatible with the Context are more accurately represented. (#101)

0.4.0 - Maintenance update

---

pyblish_qml/__main__.py
pyblish_qml/app.py
pyblish_qml/compat.py
pyblish_qml/server.py
pyblish_qml/util.py
tests/lib.py
tests/test_control.py
tests/test_util.py

For developers; this changes the way you run in debug mode.
**Previously**
```bash
$ cd pyblish-qml/pyblish_qml
$ python app.py
```
**Now**
```bash
$ python -m pyblish_qml --debug
```
In practice, it means you can no longer run the module directly from your IDE. If you can customise your IDE to run the above command instead, you should notice no other difference. Alternatively, run develop in your IDE and run from a terminal.

Python 3 compatibility

---

pyblish_qml/app.py
pyblish_qml/control.py
pyblish_qml/models.py

- Fixing major bug of having switches new and old value around

fix for #125

---

pyblish_qml/control.py

Fix for #157

---

pyblish_qml/app.py
pyblish_qml/control.py
pyblish_qml/qml/delegates/ContextDelegate.qml

In the Terminal tab. Also format the time to be more useful.

Include pyblish-base, pyblish-qml and pyblish-rpc version info

---

pyblish_qml/models.py
pyblish_qml/qml/List.qml
tests/test_control.py

fix for #172

---

setup.py

I'm not entirely sure what we should be including in the setup, so I've just stripped down the one from pyblish-base.
This is to be able to do a pip install from the repository with conda.

basic pip setup

---

README.md
pyblish_qml/control.py
pyblish_qml/host.py
pyblish_qml/models.py
pyblish_qml/rpc/formatting.py
pyblish_qml/rpc/mocking.py

#216 
pyblish-qml previously did not work with Pyblish 1.4.3 and above, due to the newly added `match` attribute of plug-ins.
This fixes that.

Implement #216

---

pyblish_qml/app.py
pyblish_qml/ipc/server.py
pyblish_qml/version.py
setup.py

1.0.0 broke compatibility with Linux, this restores it.

Linux Compatibility

---

pyblish_qml/app.py

adding in support for window position update

---

README.md
pyblish_qml/ipc/mocking.py
pyblish_qml/models.py

There was a comma missing between the default family and the families.
**Before**
**After**
Single family is as before.

Perspective cosmetics

---

pyblish_qml/app.py

My linter and OCD told me to fix this :)

Fix PEP8 issues.

---

pyblish_qml/app.py
pyblish_qml/version.py

Will need some help explaining why this fixes the issue 😕

Bug fix for standalone.

---

pyblish_qml/qml/Pyblish/ListItems/StandardActions.qml
pyblish_qml/version.py

Make unchecked items' text darker for better visual clarity.

---

pyblish_qml/qml/Pyblish/ListItems/SectionItem.qml

Uncommitted changes to https://github.com/pyblish/pyblish-qml/pull/275

Hide section

---

pyblish_qml/host.py
pyblish_qml/version.py

Fix event filter install outside supported hosts.

Hot fix for v1.8.0

---

pyblish_qml/control.py
pyblish_qml/ipc/formatting.py
pyblish_qml/models.py
pyblish_qml/qml/Overview.qml
pyblish_qml/version.py

Thought this feature(#302) is interesting, did a quick implementation for try out.
Plugins:
<details>
<summary>Example Code</summary>
```python
import pyblish.api
instances = {
"Batman": {
"family": "hero.human",
"category": "Justice League",
},
"Superman": {
"family": "hero.alien",
"category": "Justice League",
},
"Spiderman": {
"family": "hero.mutant",
"category": "Avengers",
},
"Ironman": {
"family": "hero.human",
"category": "Avengers",
},
"David": {
"family": "hero.human",
},
"Wolverine": {
"family": "hero.mutant",
},
"E.T.": {
"family": "hero.alien",
},
}
class CollectInstances(pyblish.api.ContextPlugin):
order = pyblish.api.CollectorOrder
def process(self, context):
for name, data in instances.items():
instance = context.create_instance(name)
instance.data.update(data)
context[:] = …
```

Implementing #302, Instances' visual category

---

pyblish_qml/ipc/client.py
pyblish_qml/ipc/server.py
pyblish_qml/version.py

#325 has some issues that need addressing. See #327.

Revert #325

---

pyblish_qml/control.py
pyblish_qml/models.py

This PR is related to https://github.com/pyblish/pyblish-base/pull/370 and https://github.com/pyblish/pyblish-lite/pull/116
This basically implements the new "warning" and "failedOrWarning" action types that have been added to the pyblish-base PR above.

Add support for new "warning" and "failedOrWarning" action types

---

pyblish_qml/host.py

i has create a pr for pyblish-unrea, .i creates an executeInMainThreadWithResult func for unreal module in this plugin

add a new host for UnrealEngine
